name: Testes Automatizados

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: malibu_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Instalar Dependências
      run: npm ci

    - name: Configurar Banco de Dados de Teste
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/malibu_test" > .env.test
        echo "NEXTAUTH_SECRET=test-secret-key" >> .env.test
        echo "NEXTAUTH_URL=http://localhost:3000" >> .env.test

    - name: Aplicar Migrações do Prisma
      run: npx prisma migrate deploy

    - name: Rodar Testes
      run: npm test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/malibu_test 